# SEO Tags
# https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md

title: Source Code
tagline: A blog by David Varghese
description: >- 
  Source Code is your one stop destination to articles and discussions on varied subjects from across Information Technology
url: https://blog.davidvarghese.com

social:
  name: David Varghese
  links:
    - https://github.com/dvdmtw98/
    - https://www.linkedin.com/in/david-varghese/
    - https://david-varghese.medium.com/

# End of SEO Tags

theme: jekyll-theme-chirpy

baseurl: ""

lang: en
timezone: Asia/Kolkata

avatar: assets/img/avatar.jpg

toc: true

comments:
  active: giscus
  giscus:
    repo: dvdmtw98/blog
    repo_id: R_kgDOItAOGg
    category: Comments
    category_id: DIC_kwDOItAOGs4CT6ao
    mapping: pathname
    input_position: bottom
    reactions_enabled: 1

google_analytics:
  id: G-XXXXXXXXXX
  pv:
    proxy_endpoint:
    cache_path:

pwa:
  enabled: true

paginate: 20

# ------------ The following options are not recommended to be modified ------------------

kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: true
      toc: true
      permalink: /posts/:title/
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ""
      type: tabs
    values:
      layout: page
      permalink: /:title
  - scope:
      path: assets/img/favicons
    values:
      swcache: true
  - scope:
      path: assets/js/dist
    values:
      swcache: true

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

exclude:
  - "*.gem"
  - "*.gemspec"
  - tools
  - README.md
  - CHANGELOG.md
  - LICENSE
  - gulpfile.js
  - node_modules
  - package*.json
  - scripts

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/
    
# ---------------------------------------------------------------------------
