name: Deploy Source Code to Netlify
run-name: Deploy to Netlify by @${{ github.actor }}

on:
  push:
    branches: [ main ]

jobs:
  source-code:
    name: Source Code Deployment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Chirpy
        id: checkout-chirpy
        uses: actions/checkout@v4
        with:
          repository: cotes2020/chirpy-starter
          path: chirpy
      - name: Checkout Repository
        id: checkout-repository
        uses: actions/checkout@v4
        with:
          submodules: true
          path: main
      - name: Build Source Code
        id: build-source-code
        uses: ./main/.github/actions/netlify-publish
        with:
          MEASUREMENT_ID: ${{ secrets.MEASUREMENT_ID }}
      - name: Netlify Deploy
        id: netlify-deploy
        uses: jsmrcaga/action-netlify-deploy@v2.0.0
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_DEPLOY_MESSAGE: Deployed from GitHub Action
          NETLIFY_DEPLOY_TO_PROD: true
          install_command: echo Skipping...Install not required
          build_command: echo Skipping...Build not required
          build_directory: chirpy/_site